title = "Notre-Dame de Paris"
baseURL = "/"
languageCode = "en-us"
theme = "hugo-universal-theme"


DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true



# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "asdd"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="about"
    name = "about"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="floor plan"
    name = "floor plan"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    identifier = "location"
    name = "location"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4
[[menu.main]]
    identifier = "gallery"
    name = "gallery"
    url  = "/gallery/"
    weight = 5
[[menu.main]]
    identifier = "specifications"
    name = "specifications"
    url  = "/#specifications"
    weight = 6



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/xleawnny"
    contact_form_ajax = false

    contact_us = "contact us"
    email = "enquiries@assasdunia.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    copyright= "*All drawings and illustrations herein are artist’s impressions only. All plans, specifications, measurements and information contained herein are subject to variations, amendments and changes as may be required by the relevant authorities or project architect without prior notification to purchase and cannot form part of an offer or contract.<br><br>COPYRIGHT © 2021 ASAS DUNIA BERHAD. ALL RIGHTS RESERVED."

    download = "https://abc.com/doanload"
    book_now = "contact"

[params.add1]
    name= "Penang Sales Office"
    text = "Wisma Asas, No.228, Lebuh Chulia,<br>10200 Penang."
    tel="04-255 9999"
    fax="04-255 9888"
[params.add2]
    name= "Hijauan Hills Sales Gallery"
    text = "No.2, Jalan Hijauan Hills 3, Hijauan Hills,<br>14120 Simpang Ampat, Penang."
    tel="04-563 3999"
    fax="04-563 1999"
[params.floor_plan]
    land_area= "19’x 71.85’"
    built_up = "19’x 43.8’" 
    floor_plan = "img/Floor_plan.png"
[params.site_plan]
    img = "img/Site_plan.png"
    icon = "low-den"
    digit = "50"
    quantity = "Units"
    map1 = "img/map1.png"
    map2 = "img/map2.png"
  

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All fal are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.home]
    enable = true
    title = "phase 6"
    subtitle = "FREEHOLD & GUARDED <br>Sungai Bakap"
    name = "iris"
    size = "1,365 sqft"
    type= "SINGLE STOREY <br> TERRACE HOUSE"
    
[params.description]
    title = "Peace and Tranquility, Enclaved in Greenery."   
    description = "<p>The dream of having a place of your own called home is made a reality with Iris. The single storey terrace homes (Iris) blooms within an established guarded community, Hijauan Valdor, rich with healthy flourishing greens, clusters of linear parks and luxury of space with its low density concept. </p><br><p>Iris in Hijauan Valdor, situated near the 2nd Penang Bridge for quick access to the Island, while also connected to matured township like Alma, Simpang Ampat, Sungai Bakap, Nibong Tebal and the fast-developing Batu Kawan, all providing easy accessibility to shopping malls, schools, employment, social and other daily needs. </p><br><p>All this can be yours without breaking your bank!</p>" 
[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

[params.access]
    [[params.access.main]]
        name = "Schools"
        icon = "book"
        [[params.access.main.sub]]
            name = "SMJK(C) Jit Sin 2"
            distance = "2km"
        [[params.access.main.sub]]
            name = "SMK Valdor"
            distance = "2km"
        [[params.access.main.sub]]
            name = "SJK(C) Kampung Valdorr"
            distance = "2km"
    [[params.access.main]]
        name = "Access to Penang Island"
        icon = "bridge"
        [[params.access.main.sub]]
            name = "2nd Penang Bridge"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Penang Bridge"
            distance = "2km"
    [[params.access.main]]
        name = "Markets"
        icon = "market"
        [[params.access.main.sub]]
            name = "Valdor Market"
            distance = "2km"
        [[params.access.main.sub]]
            name = "TESCO"
            distance = "2km"
        [[params.access.main.sub]]
            name = "JUSCO"
            distance = "2km"
    [[params.access.main]]
        name = "Neighbouring Township"
        icon = "township"
        [[params.access.main.sub]]
            name = "Batu Kawan"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Bukit Mertajam"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Alma"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Simpang Ampat"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Sungai Bakap"
            distance = "2km"
        [[params.access.main.sub]]
            name = "Nibong Tebal"
            distance = "2km"
[params.gallery]
    [[params.gallery.img]]
    img = "/img/gallery/IRIS-5.png"
    [[params.gallery.img]]
    img = "/img/gallery/IRIS-6.png"
    [[params.gallery.img]]
    img = "/img/gallery/IRIS-7.png"
    [[params.gallery.img]]
    img = "/img/gallery/IRIS-8.png"
    [[params.gallery.img]]
    img = "/img/gallery/IRIS-9.png"

[params.specifications]
    [[params.specifications.img]]
    img = "/img/text.png"
    [[params.specifications.img]]
    img = "/img/text 2.png"
    [[params.specifications.img]]
    img = "/img/text.png"
    [[params.specifications.img]]
    img = "/img/text 2.png"