title = "Hijauan Valdor - Phase 6"
baseURL = "https://dbpo.shinajii.com/hvp6"
languageCode = "en-us"
theme = "hugo-universal-theme"


DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true



# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "asdd"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="about"
    name = "about"
    url  = "#about"
    weight = 1

[[menu.main]]
    identifier="floor plan"
    name = "floor plan"
    url  = "#floor-plan"
    weight = 2

[[menu.main]]
    identifier = "location"
    name = "site plan"
    url  = "#site-plan"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Location"
    url  = "#footer"
    weight = 4
[[menu.main]]
    identifier = "gallery"
    name = "gallery"
    url  = "#gallery"
    weight = 5
[[menu.main]]
    identifier = "specifications"
    name = "specifications"
    url  = "#specifications"
    weight = 6


[params]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "./email.php"
    contact_form_ajax = false

    contact_us = "contact us"
    email = "enquiries@assasdunia.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    copyright= "*All drawings and illustrations herein are artist’s impressions only. All plans, specifications, measurements and information contained herein are subject to variations, amendments and changes as may be required by the relevant authorities or project architect without prior notification to purchase and cannot form part of an offer or contract.<br><br>COPYRIGHT © {year} ASAS DUNIA BERHAD. ALL RIGHTS RESERVED."

    download = "https://abc.com/doanload"
    book_now = "contact"

[params.add1]
    name= "Penang Sales Office"
    text = "Wisma Asas, No.228, Lebuh Chulia,<br>10200 Penang."
    tel="04-255 9999"
    fax="04-255 9888"
[params.add2]
    name= "Hijauan Hills Sales Gallery"
    text = "No.2, Jalan Hijauan Hills 3, Hijauan Hills,<br>14120 Simpang Ampat, Penang."
    tel="04-563 3999"
    fax="04-563 1999"
[params.floor_plan]
    land_area= "19’x 71.85’"
    built_up = "19’x 43.8’" 
    floor_plan = "Floor_plan"
[params.site_plan]
    img = "Site_plan"
    icon = "low-den"
    digit = "50"
    quantity = "Units"
    map1 = "map1"
    map2 = "map2"

# Enable or disable top bar with social icons

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.


[params.home]
    enable = true
    title = "phase 6"
    subtitle = "FREEHOLD & GUARDED <br>Sungai Bakap"
    name = "iris"
    size = "1,365 sqft"
    type= "SINGLE STOREY <br> TERRACE HOUSE"
    
[params.description]
    title = "Peace and Tranquility, Enclaved in Greenery."   
    description = "<p>The dream of having a place of your own called home is made a reality with Iris. The single storey terrace homes (Iris) blooms within an established guarded community, Hijauan Valdor, rich with healthy flourishing greens, clusters of linear parks and luxury of space with its low density concept. </p><br><p>Iris in Hijauan Valdor, situated near the 2nd Penang Bridge for quick access to the Island, while also connected to matured township like Alma, Simpang Ampat, Sungai Bakap, Nibong Tebal and the fast-developing Batu Kawan, all providing easy accessibility to shopping malls, schools, employment, social and other daily needs. </p><br><p>All this can be yours without breaking your bank!</p>" 

[params.access]
    [[params.access.main]]
        name = "Schools"
        icon = "book"
        [[params.access.main.sub]]
            name = "SMJK(C) Jit Sin 2"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "SMK Valdor"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "SJK(C) Kampung Valdorr"
            distance = "2km"
            time = "2"
    [[params.access.main]]
        name = "Access to Penang Island"
        icon = "bridge"
        [[params.access.main.sub]]
            name = "2nd Penang Bridge"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Penang Bridge"
            distance = "2km"
            time = "2"
    [[params.access.main]]
        name = "Markets"
        icon = "market"
        [[params.access.main.sub]]
            name = "Valdor Market"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "TESCO"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "JUSCO"
            distance = "2km"
            time = "2"
    [[params.access.main]]
        name = "Neighbouring Township"
        icon = "township"
        [[params.access.main.sub]]
            name = "Batu Kawan"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Bukit Mertajam"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Alma"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Simpang Ampat"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Sungai Bakap"
            distance = "2km"
            time = "2"
        [[params.access.main.sub]]
            name = "Nibong Tebal"
            distance = "2km"
            time = "2"
[params.gallery]
    [[params.gallery.img]]
    img = "IRIS-5"
    [[params.gallery.img]]
    img = "IRIS-6"
    [[params.gallery.img]]
    img = "IRIS-7"
    [[params.gallery.img]]
    img = "IRIS-8"
    [[params.gallery.img]]
    img = "IRIS-9"

[params.specifications]
    [[params.specifications.img]]
    img = "text"
    [[params.specifications.img]]
    img = "text2"
    [[params.specifications.img]]
    img = "text"
    [[params.specifications.img]]
    img = "text2"